src/Entity/Town.php
<?php

namespace App\Entity;

use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Event\LifecycleEventArgs;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\OrderBy;
use Doctrine\ORM\ORMException;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TownRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Town
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private ?int $id = null;

    /**
     * @ORM\Column(type="string", length=190)
     */
    private ?string $name = null;

    /**
     * @ORM\Column(type="string", length=8)
     */
    private ?string $language = null;

    /**
     * @ORM\Column(type="integer")
     */
    private ?int $population = null;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private ?string $wordsOfHeroes = null;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Citizen", mappedBy="town", orphanRemoval=true, cascade={"persist", "remove"})
     * @OrderBy({"alive" = "DESC", "id" = "ASC"})
     */
    private $citizens;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Inventory", inversedBy="town", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private ?Inventory $bank = null;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\TownClass", inversedBy="towns")
     * @ORM\JoinColumn(nullable=false)
     */
    private ?TownClass $type = null;

    /**
     * @ORM\Column(type="integer")
     */
    private int $day = 1;

    /**
     * @ORM\Column(type="integer")
     */
    private ?int $well = 0;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Zone", mappedBy="town", orphanRemoval=true, cascade={"persist", "remove"})
     */
    private $zones;

    /**
     * @ORM\Column(type="boolean")
     */
    private bool $door = false;

    /**
     * @ORM\Column(type="boolean")
     */
    private bool $chaos = false;

    /**
     * @ORM\Column(type="boolean")
     */
    private bool $devastated = false;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Building", mappedBy="town", orphanRemoval=true, cascade={"persist", "remove"})
     * @ORM\OrderBy({"position" = "ASC"})
     */
    private $buildings;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\ZombieEstimation", mappedBy="town", orphanRemoval=true, cascade={"persist"})
     */
    private $zombieEstimations;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Gazette", mappedBy="town", orphanRemoval=true, cascade={"persist"})
     */
    private $gazettes;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Forum", mappedBy="town", cascade={"persist", "remove"})
     */
    private ?Forum $forum = null;

    /**
     * @ORM\Column(type="array", nullable=true)
     */
    private array $conf = [];

    /**
     * @ORM\Column(type="integer")
     */
    private int $soulDefense = 0;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Season", inversedBy="towns")
     */
    private ?Season $season = null;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\CitizenWatch", mappedBy="town", orphanRemoval=true)
     */
    private $citizenWatches;

    /**
     * @ORM\OneToOne(targetEntity=TownRankingProxy::class, mappedBy="town", cascade={"persist"})
     * @ORM\JoinColumn(nullable=true, onDelete="SET NULL")
     */
    private ?TownRankingProxy $rankingEntry = null;

    /**
     * @ORM\ManyToOne(targetEntity=AttackSchedule::class)
     */
    private $lastAttack;

    /**
     * @ORM\Column(type="integer")
     */
    private int $attackFails = 0;

    /**
     * @ORM\Column(type="string", length=90, nullable=true)
     */
    private ?string $password = null;

    /**
     * @ORM\Column(type="integer")
     */
    private int $dayWithoutAttack = 0;

    /**
     * @ORM\ManyToOne(targetEntity=User::class)
     */
    private ?User $creator = null;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\TownLogEntry", mappedBy="town", cascade={"remove"})
     */
    private $_townLogEntries;

    /**
     * @ORM\Column(type="string", length=24, nullable=true)
     */
    private ?string $deriveConfigFrom = null;

    /**
     * @ORM\Column(type="integer")
     */
    private $insurrectionProgress = 0;

    public function __construct()
    {
        $this->citizens = new ArrayCollection();
        $this->zones = new ArrayCollection();
        $this->buildings = new ArrayCollection();
        $this->zombieEstimations = new ArrayCollection();
        $this->citizenWatches = new ArrayCollection();
        $this->_townLogEntries = new ArrayCollection();
        $this->gazettes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getLanguage(): ?string
    {
        return $this->language;
    }

    public function setLanguage(string $language): self
    {
        $this->language = $language;

        return $this;
    }

    public function getWordsOfHeroes(): ?string
    {
        return $this->wordsOfHeroes;
    }

    public function setWordsOfHeroes(string $wordsOfHeroes): self
    {
        $this->wordsOfHeroes = $wordsOfHeroes;

        return $this;
    }

    public function getPopulation(): ?int
    {
        return $this->population;
    }

    public function setPopulation(int $population): self
    {
        $this->population = $population;

        return $this;
    }

    public function getCitizenCount(): int {
        return $this->getCitizens()->count();
    }

    public function getAliveCitizenCount(): int {
        $cc = 0;
        foreach ($this->getCitizens() as $c)
            if ($c->getAlive()) $cc++;
            return $cc;
    }

    public function getActiveCitizenCount(): int {
        $cc = 0;
        foreach ($this->getCitizens() as $c)
            if ($c->getActive()) $cc++;
        return $cc;
    }

    public function isOpen(): bool {
        return $this->getDay() === 1 && $this->getCitizenCount() < $this->getPopulation();
    }

    public function userInTown(User $user): bool {
        foreach ($this->getCitizens() as $citizen) {
            if($citizen->getUser() === $user)
                return true;
        }
        return false;
    }

    /**
     * @return Collection|Citizen[]
     */
    public function getCitizens(): Collection
    {
        return $this->citizens;
    }

    public function addCitizen(Citizen $citizen): self
    {
        if (!$this->citizens->contains($citizen)) {
            $this->citizens[] = $citizen;
            $citizen->setTown($this);
        }

        return $this;
    }

    public function removeCitizen(Citizen $citizen): self
    {
        if ($this->citizens->contains($citizen)) {
            $this->citizens->removeElement($citizen);
            // set the owning side to null (unless already changed)
            if ($citizen->getTown() === $this) {
                $citizen->setTown(null);
            }
        }

        return $this;
    }

    public function getBank(): ?Inventory
    {
        return $this->bank;
    }

    public function setBank(Inventory $bank): self
    {
        $this->bank = $bank;

        return $this;
    }

    public function getType(): ?TownClass
    {
        return $this->type;
    }

    public function setType(?TownClass $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getDay(): ?int
    {
        return $this->day;
    }

    public function setDay(int $day): self
    {
        $this->day = $day;

        return $this;
    }

    public function getWell(): ?int
    {
        return $this->well;
    }

    public function setWell(int $well): self
    {
        $this->well = $well;

        return $this;
    }

    /**
     * @return Collection|Zone[]
     */
    public function getZones(): Collection
    {
        return $this->zones;
    }

    public function addZone(Zone $zone): self
    {
        if (!$this->zones->contains($zone)) {
            $this->zones[] = $zone;
            $zone->setTown($this);
        }

        return $this;
    }

    public function removeZone(Zone $zone): self
    {
        if ($this->zones->contains($zone)) {
            $this->zones->removeElement($zone);
            // set the owning side to null (unless already changed)
            if ($zone->getTown() === $this) {
                $zone->setTown(null);
            }
        }

        return $this;
    }

    public function getDoor(): ?bool
    {
        return $this->door;
    }

    public function setDoor(bool $door): self
    {
        $this->door = $door;

        return $this;
    }

    public function getChaos(): ?bool
    {
        return $this->chaos;
    }

    public function setChaos(bool $chaos): self
    {
        $this->chaos = $chaos;

        return $this;
    }


    public function getForum(): ?Forum
    {
        return $this->forum;
    }

    public function setForum(?Forum $forum): self
    {
        $this->forum = $forum;

        // set (or unset) the owning side of the relation if necessary
        $newTown = null === $forum ? null : $this;
        if ($forum->getTown() !== $newTown) {
            $forum->setTown($newTown);
        }

        return $this;
    }

    public function getDevastated(): ?bool
    {
        return $this->devastated;
    }

    public function setDevastated(bool $devastated): self
    {
        $this->devastated = $devastated;

        return $this;
    }

    /**
     * @return Collection|Building[]
     */
    public function getBuildings(): Collection
    {
        return $this->buildings;
    }

    public function addBuilding(Building $building): self
    {
        if (!$this->buildings->contains($building)) {

templates/ajax/admin/towns/footer.html.twig
<div class="row">
    <div class="cell padded rw-12 rw-sm-12">
        <div id="towns-list-admin">
            <h5>{{'Suche:'|trans({}, "admin")}}</h5>
            {% include 'ajax/admin/snippets/town_search.html.twig' %}
        </div>
    </div>
</div>
{% block js %}
    <script>
        let typingTimer, doneTypingInterval = 500;
        let searchBox = document.getElementById('town-search');

        const userSearchHandler = function() {
            $.ajax.background().load(
                document.getElementById('towns-list'),
                '{{ path(search_controller) }}',
                false,
                {'name': searchBox.value}
            );
        };

        const townSearchHandlerUp = function () {
            clearTimeout(typingTimer);
            typingTimer = setTimeout(userSearchHandler, doneTypingInterval);
        };

        const townSearchHandlerDown = function () {
            clearTimeout(typingTimer);
        };

        searchBox.addEventListener('keyup', townSearchHandlerUp);
        searchBox.addEventListener('keydown', townSearchHandlerDown);
    </script>
{% endblock %}

templates/ajax/admin/towns/list.html.twig
{% extends "ajax/ajax.html.twig" %}
{% block title %}{{ 'Aktuelle Städte'|trans({}, 'admin')|raw }}{% endblock %}
{% block ajax %}
    <div class="row">
        <div class="cell padded rw-12">
            <ul class="tabs plain">
                <li class="tab {% if admin_tab =='towns' %}selected{% endif %}">
                    <div class="tab-link" x-ajax-href="{{ path('admin_town_list') }}"><span>{{ 'Aktuelle Städte'|trans({}, 'admin') }}</span></div>
                </li>
                <li class="tab {% if admin_tab =='old_towns' %}selected{% endif %}">
                    <div class="tab-link" x-ajax-href="{{ path('admin_old_town_list') }}"><span>{{ 'Fertige Städte'|trans({}, 'admin') }}</span></div>
                </li>
            </ul>
            <h5>{{ 'Bürger nach Sprache'|trans({}, 'admin') }}</h5>
            <div class="row">
                {% for stat in citizen_stats %}
                <div class="cell rw-2 center">
                        <img src="{{ asset("build/images/lang/" ~ stat.language ~".png") }}" alt="{{ stat.language }}" /><br />
                        {{ stat.count }}
                </div>
                {% endfor %}
            </div>
            <h5>{{ 'Liste aller Städte'|trans({},'admin') }}</h5>
            <div class="row-table">
                <div class="row header">
                    <div class="cell padded rw-1">{{ 'ID'|trans({},'admin') }}</div>
                    <div class="cell padded rw-5">{{ 'Stadtname'|trans({},'admin') }}</div>
                    <div class="cell padded rw-1">{{ 'Tag'|trans({},'admin') }}</div>
                    <div class="cell padded rw-2">{{ 'Pop.'|trans({},'admin') }}</div>
                    <div class="cell padded rw-3 right">{{ 'Aktionen'|trans({},'admin') }}</div>
                </div>
                {# @var towns \App\Entity\Town[] #}
                {% for town in towns %}
                    <div class="row">
                        <div class="cell padded rw-1">
                            {{ town.id }}<br />
                            {% if town.language is not empty %}
                                <span class="language"><img src="{{ asset("build/images/lang/" ~ town.language ~".png") }}" alt="{{ town.language }}" /></span>
                            {% endif %}
                        </div>
                        <div class="cell padded rw-5">
                            {{ town.name }}<br />
                            {% if town.attackFails >= 3 %}<span style="color: red">{{ 'Quarantäne'|trans({},'game') }}</span> {% endif %}<span class="small">{% if town.open %}<i class="fa fa-door-open"></i> {% endif %}{{ town.type.label|trans({},'game') }}</span>
                        </div>
                        <div class="cell padded rw-1">{{ town.day }}</div>
                        <div class="cell padded rw-2">
                            {{ town.citizenCount }} / {{ town.population }} {% if town.citizenCount < town.population %}<i title="{{ 'Geöffnet'|trans({},'admin') }}" class="small fa fa-door-open"></i>{% endif %}<br />
                            <span title="{{ 'Leben'|trans({},'admin') }}" class="small"><i class="fa fa-users"></i> {{ town.aliveCitizenCount }}</span> <span title="{{ 'Tot'|trans({},'admin') }}" class="small"><i class="fa fa-skull"></i> {{ town.citizenCount - town.aliveCitizenCount }}</span> <span title="{{ 'Getrennt'|trans({},'admin') }}" class="small"><i class="fa fa-user-slash"></i> {{ town.citizenCount - town.activeCitizenCount }}</span>
                        </div>
                        <div class="cell padded rw-3 right">
                            <button x-ajax-href="{{ path('admin_town_explorer', {id: town.id}) }}" class="small inline">{{ 'Details'|trans({},'admin') }}...</button>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
    {% embed "ajax/admin/towns/footer.html.twig" with {'search_controller': 'admin_towns_fuzzyfind'} %}{% endembed %}
{% endblock %}
{% block js %}
    {{ parent() }}
    <script>
    </script>
{% endblock %}

templates/ajax/admin/towns/log.html.twig
<div class="log-container">
    <div class="log" x-log-default-provided="{% if log_content is defined %}1{% else %}0{% endif %}" x-log-source="{{ log_source }}">
        <div class="log-content">
            {% if log_content is defined %}
                {{ log_content|raw }}
                {% if log_content|length > 255 %}
                    <div class="log-complete-link">{{ 'Alle Einträge anzeigen'|trans({},'game') }}</div>
                    <div class="log-spinner hidden"><i class="fa fa-pulse fa-spinner"></i> {{ random(['Akteneinsicht wird beantragt...'|trans({},'game'),'Protokolle werden analysiert...'|trans({},'game'),'Überwachungsapparat wird ausgewertet...'|trans({},'game'),'Belastende Beweise werden übermittelt...'|trans({},'game')]) }}</div>
                {% endif %}
            {% endif %}
        </div>
    </div>
    {% if day is defined %}
        <div class="log-day-select">
            <div><div class="tab" x-page-current="{{ day }}" x-page-min="1" x-page-max="{{ day }}"><div class="control"><i class="fa fa-arrow-left"></i></div><div>{{ 'Tag'|trans({}, 'game') }} <span>{{ day }}</span></div><div class="control"><i class="fa fa-arrow-right"></i></div></div></div>
        </div>
    {% endif %}
</div>

templates/ajax/admin/towns/log_content.html.twig
{# @var entries \App\Entity\TownLogEntry[] #}
{% if entries|length == 0 %}
    <i>{{ 'Heute ist nichts Erwähnenswertes passiert...'|trans({},'game') }}</i>
{% else %}
    {% for entry in entries %}
        <div class="log-entry log-entry-type-{{ entry.type }} log-entry-class-{{ entry.class }}">
            <span class="log-part-time">{{ entry.timestamp.format('G:i') }}</span>
            <span class="log-part-content {% if entry.hidden %}log-part-entry-hidden{% endif %}">{% if entry.hidden %}<img src="{{ asset('build/images/icons/small_warning.gif') }}" />{% endif %} {{ entry.text|raw }} {% if entry.hiddenBy is not null %}(Hidden by {{ entry.hiddenBy.user.name }}){% endif %}</span>
        </div>
    {% endfor %}

    <script>
    let remove_log = document.querySelectorAll('.remove-entry');
        for(let i = 0 ; i < remove_log.length ; i++){
            remove_log[i].addEventListener('click', function(){
                $.ajax.background().easySend("{{path('delete_log_entry')}}", {'log_entry_id': this.getAttribute('x-entry-id')}, function(){
                	let log_boxes = document.querySelectorAll('.log-container');
                	for (let i = 0; i < log_boxes.length; i++) {
                		let log = log_boxes[i].querySelector( '.log' );
                		const url = log.getAttribute('x-log-source');
                		let content_box = log.querySelectorAll('.log-content');
                		$.ajax.background().load( content_box[0], url, false, {day: -1} );
                	}
                });
            });
        }
    </script>
{% endif %}
{{ include('ajax/flash.html.twig') }}

templates/ajax/admin/towns/old_town_explorer.html.twig
{% extends "ajax/ajax.html.twig" %}
{% block title %}{{'Stadt %townname%'|trans({'%townname%': town.name}, 'admin')}}{% endblock %}
{% block ajax %}
    {% macro valuelist(prop,val) %}
        <div class="row">
            <div class="cell rw-4"><b>{{ prop }}</b></div>
            <div class="cell rw-8">
                {% if val is same as(true) %}
                    {{ 'Ja'|trans({},'admin') }}
                {% elseif val is same as(false)  %}
                    {{ 'Nein'|trans({},'admin') }}
                {% else %}
                    {{ val }}
                {% endif %}
            </div>
        </div>
    {% endmacro %}

    <div class="row">
        <div class="cell padded rw-12">
            <ul class="tabs plain" x-tab-group="admin-town" x-tab-control x-tab-default="{{ tab }}">
            	<div class="tab-floater">
                <li class="tab" x-tab-id="dash"><div class="tab-link">{{ 'Übersicht'|trans({},'admin') }}</div></li>
                <li class="tab" x-tab-id="citizens"><div class="tab-link">{{ 'Bürger'|trans({},'admin') }}</div></li>
                </div>
            </ul>
            {# @var town \App\Entity\TownRankingEntry #}
            <div x-tab-group="admin-town" x-tab-id="dash" x-tab-target>
                <div class="row">
                    <div class="cell padded rw-6 rw-sm-12">
                        {{ _self.valuelist('ID'|trans({},'admin'),         town.imported ? town.baseID : town.id) }}
                        {{ _self.valuelist('Stadtname'|trans({},'admin'),  town.name) }}
                        {{ _self.valuelist('Sprache'|trans({},'admin'),    town.language) }}
                        {{ _self.valuelist('Typ'|trans({},'admin'),        town.type.label|trans({},'game')) }}
                        {{ _self.valuelist('Population'|trans({},'admin'), town.population) }}
                        {{ _self.valuelist('Saison'|trans({},'admin'),     town.season ? town.season.number : '--') }}
                        {{ _self.valuelist('Tag'|trans({},'admin'),        town.days) }}
                        {{ _self.valuelist('Importiert'|trans({},'admin'), town.imported) }}

                    </div>
                </div>
            </div>
            <div x-tab-group="admin-town" x-tab-id="citizens" x-tab-target>
                <div class="row">
                    <div class="cell padded rw-5 rw-sm-12">
                        <div class="row-table citizens-list">
                            <div class="row header">
                                <div class="padded cell left rw-12">{{ 'Bürger'|trans({},'game') }}</div>
                            </div>
                            {% for citizen in town.citizens|sort((a,b) => b.day <=> a.day) %}
                                {# @var \App\Entity\Citizen citizen  #}
                                <div class="row-flex stretch pointer" style="max-height: 100px;">
                                    <div class="cell factor-0 avatar ua-{{ random(0,9) }}" style="flex-basis: 90px; background: url('{{ citizen.user.avatar ? path('app_web_avatar', {'uid': citizen.user.id, 'name': citizen.user.avatar.smallName, 'ext': citizen.user.avatar.format}) : asset('build/images/forum/empty_avatar.gif') }}') center/cover no-repeat;" x-ajax-href="{{ url('admin_users_citizen_view', {id: citizen.user.id}) }}">&nbsp;</div>
                                    <div class="cell factor-0 citizen-dead" style="flex-basis: 8px;" x-ajax-href="{{ url('admin_users_citizen_view', {id: citizen.user.id}) }}">&nbsp;</div>
                                    
                                    <div class="padded cell rw-4 factor-1 small content-center-vertical citizen-box citizen-box-name">
                                        <img alt="{{ 'Tot!'|trans({},'game') }}" src="{{ asset('build/images/professions/death.gif') }}" />
                                        <a class="link" href="{{ url('admin_users_citizen_view', {id: citizen.user.id}) }}">
                                            <b class="citizen-name">{{ citizen.user.name }}</b>
                                        </a>&nbsp;
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="cell rw-7 rw-sm-12 padded">
                        {% if is_granted("ROLE_ADMIN") %}
                        <div class="padded cell">
                            <label for="selectPicto">{{'Eine Auszeichnungen auswählen:'|trans({}, 'admin')}}</label>
                            <select id="selectPicto">
                                {% for pictoPrototype in pictoPrototypes %}
                                    <option value="{{pictoPrototype.id}}">{{ pictoPrototype.label|trans({}, 'game') }}</option>
                                {% endfor %}
                            </select>
                            <label for="numberPicto">
                                {{'Anzahl der Auszeichnungen:'|trans({}, 'admin')}}
                            </label>
                            <input type="number" id="numberPicto" value="1"/>
                            <br />
                            <button id="givebtn">{{'Vergeben!'|trans({}, 'admin')}}</button>
                        </div>
                        <br />
                        {% endif %}
                    </div>
                </div>
            </div>
            <br />
            <div class="row">
                <div class="cell rw-3 ro-9">
                    <button x-ajax-href="{{ path('admin_old_town_list') }}">{{ 'Stadtübersicht'|trans({},'admin') }}</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block js %}
    {{ parent() }}
    <script>
        (function() {

           {% if is_granted("ROLE_ADMIN") %}

            let givebtn = document.getElementById("givebtn");
            if (givebtn) givebtn.addEventListener('click', function(){
                let number = document.getElementById("numberPicto").value;
                if(isNaN(number)) number = 1;

                let picto = document.getElementById('selectPicto').value;

                $.ajax.easySend('{{ path('admin_town_give_picto', {id: town.id}) }}', {
                        prototype: picto, number: number
                    },
                    function () {
                        $.ajax.load(null, '{{ path('admin_old_town_explorer', {id: town.id, tab: "citizens"}) }}', true);
                    }
                );
            });

            {% endif %}
        })();

    </script>
{% endblock %}

templates/ajax/admin/towns/old_towns_list.html.twig
{% extends "ajax/ajax.html.twig" %}
{% block title %}{{ 'Fertige Städte'|trans({}, 'admin') }}{% endblock %}
{% block ajax %}
    <div class="row">
        <div class="cell padded rw-12">
            <ul class="tabs plain">
                <li class="tab {% if admin_tab =='towns' %}selected{% endif %}">
                    <div class="tab-link" x-ajax-href="{{ path('admin_town_list') }}"><span>{{ 'Aktuelle Städte'|trans({}, 'admin') }}</span></div>
                </li>
                <li class="tab {% if admin_tab =='old_towns' %}selected{% endif %}">
                    <div class="tab-link" x-ajax-href="{{ path('admin_old_town_list') }}"><span>{{ 'Fertige Städte'|trans({}, 'admin') }}</span></div>
                </li>
            </ul>
            <h5>{{ 'Liste aller Städte'|trans({},'admin') }}</h5>
            <div class="rw-2">
                {{ 'Seite %page%/%total%'|trans({'%page%': currentPage, '%total%': pagesCount}, 'admin') }}
            </div>
            <div class="rw-8">
                {% if currentPage > 1 %}
                <a class="link" x-ajax-href="{{ path('admin_old_town_list', {page: currentPage - 1}) }}"> « </a>
                {% endif %}
                {% for i in currentPage - 3..currentPage - 1 %}
                    {% if i > 0 %}
                        <a class="link" x-ajax-href="{{ path('admin_old_town_list', {page: i}) }}">{{ i }}</a>
                    {% endif %}
                {% endfor %}
                {{ currentPage }}
                {% for i in currentPage + 1..currentPage + 3 %}
                    {% if i <= pagesCount %}
                        <a class="link" x-ajax-href="{{ path('admin_old_town_list', {page: i}) }}">{{ i }}</a>
                    {% endif %}
                {% endfor %}
                {% if currentPage < pagesCount %}
                    <a class="link" x-ajax-href="{{ path('admin_old_town_list', {page: currentPage + 1}) }}"> » </a>
                {% endif %}
            </div>
            <div class="row-table">
                <div class="row header">
                    <div class="cell padded rw-1">{{ 'ID'|trans({},'admin') }}</div>
                    <div class="cell padded rw-5">{{ 'Stadtname'|trans({},'admin') }}</div>
                    <div class="cell padded rw-1">{{ 'Tag'|trans({},'admin') }}</div>
                    <div class="cell padded rw-1">{{ 'Pop.'|trans({},'admin') }}</div>
                    <div class="cell padded rw-1">{{ 'Importiert'|trans({},'admin') }}</div>
                    <div class="cell padded rw-3 right">{{ 'Aktionen'|trans({},'admin') }}</div>
                </div>
                {# @var towns \App\Entity\TownRankingEntry[] #}
                {% for town in towns %}
                    <div class="row">
                        <div class="cell padded rw-1">
                            {% if town.imported %}
                                {{ town.baseID }}
                            {% else %}
                                {{ town.id }}
                            {% endif %}<br />
                            {% if town.language is not empty %}
                                <span class="language"><img src="{{ asset("build/images/lang/" ~ town.language ~".png") }}" alt="{{ town.language }}" /></span>
                            {% endif %}
                        </div>
                        <div class="cell padded rw-5">
                            {{ town.name }}
                        </div>
                        <div class="cell padded rw-1">{{ town.days }}</div>
                        <div class="cell padded rw-1">
                            {{ town.citizens|length }} / {{ town.population }}
                        </div>
                        <div class="cell padded rw-1">{% if town.imported %}{{ 'Ja'|trans({}, 'admin') }}{% else %}{{ 'Nein'|trans({}, 'admin') }}{% endif %}</div>
                        <div class="cell padded rw-3 right">
                            <button x-ajax-href="{{ path('admin_old_town_explorer', {id: town.id}) }}" class="small inline">{{ 'Details'|trans({},'admin') }}...</button>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
    {% embed "ajax/admin/towns/footer.html.twig" with {'search_controller': 'admin_old_towns_fuzzyfind'} %}{% endembed %}

{% endblock %}
{% block js %}
    {{ parent() }}
    <script>
    </script>
{% endblock %}

templates/ajax/admin/towns/townlist.html.twig
{% block ajax %}
    {% for town in towns %}
        <div class="towns-list-entry" x-town-id="{{ town.id }}" x-town-name="{{ town.name }}" x-admin-url="{{ url(target, {id: town.id}) }}">
            <div {% if not nohref %}x-ajax-href="{{ url(target, {id: town.id}) }}" x-ajax-target="#content"{% endif %}>
                <span class="language"><img src="{{ asset("build/images/lang/" ~ town.language ~".png") }}" alt="{{ town.language }}" /></span> {{ town.name }}
            </div>
        </div>
    {% endfor %}
{% endblock %}