src/Controller/GameController.php
<?php

namespace App\Controller;

use App\Annotations\GateKeeperProfile;
use App\Entity\ActionCounter;
use App\Entity\Citizen;
use App\Entity\CitizenProfession;
use App\Entity\CauseOfDeath;
use App\Entity\Complaint;
use App\Entity\Gazette;
use App\Entity\GazetteEntryTemplate;
use App\Entity\GazetteLogEntry;
use App\Entity\HeroicActionPrototype;
use App\Entity\HeroSkillPrototype;
use App\Entity\ItemPrototype;
use App\Entity\LogEntryTemplate;
use App\Entity\SpecialActionPrototype;
use App\Entity\TownLogEntry;
use App\Entity\User;
use App\Entity\Zone;
use App\Response\AjaxResponse;
use App\Service\CitizenHandler;
use App\Service\ConfMaster;
use App\Service\ErrorHelper;
use App\Service\InventoryHandler;
use App\Service\ItemFactory;
use App\Service\JSONRequestParser;
use App\Service\LogTemplateHandler;
use App\Service\PictoHandler;
use App\Service\TimeKeeperService;
use App\Service\TownHandler;
use App\Service\UserHandler;
use App\Structures\ItemRequest;
use App\Structures\TownConf;
use App\Translation\T;
use Doctrine\Common\Collections\Criteria;
use Doctrine\ORM\EntityManagerInterface;
use Exception;
use DateTime;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Contracts\Translation\TranslatorInterface;

/**
 * @Route("/",condition="request.isXmlHttpRequest()")
 * @GateKeeperProfile(only_incarnated=true)
 * @method User getUser()
 */
class GameController extends CustomAbstractController
{
    protected $logTemplateHandler;
    protected TownHandler $town_handler;
    private $user_handler;
    protected PictoHandler $picto_handler;

    public function __construct(EntityManagerInterface $em, TranslatorInterface $translator, LogTemplateHandler $lth, TimeKeeperService $tk, CitizenHandler $ch, UserHandler $uh, TownHandler $th, ConfMaster $conf, PictoHandler $ph, InventoryHandler $ih)
    {
        parent::__construct($conf, $em, $tk, $ch, $ih, $translator);
        $this->logTemplateHandler = $lth;
        $this->user_handler = $uh;
        $this->town_handler = $th;
        $this->picto_handler = $ph;
    }

    protected function getActiveCitizen(): Citizen {
        return $this->entity_manager->getRepository(Citizen::class)->findActiveByUser($this->getUser());
    }

    protected function renderLog( ?int $day, $citizen = null, $zone = null, ?int $type = null, ?int $max = null ): Response {
        $entries = [];
        /** @var TownLogEntry $entity */
        foreach ($this->entity_manager->getRepository(TownLogEntry::class)->findByFilter($this->getActiveCitizen()->getTown(),$day, $citizen, $zone, $type, $max ) as $idx=>$entity) {
            /** @var LogEntryTemplate $template */
            $template = $entity->getLogEntryTemplate();
            if (!$template)
                continue;
            $entityVariables = $entity->getVariables();
            $entries[$idx]['timestamp'] = $entity->getTimestamp();
            $entries[$idx]['class'] = $template->getClass();
            $entries[$idx]['type'] = $template->getType();
            $entries[$idx]['id'] = $entity->getId();
            $entries[$idx]['hidden'] = $entity->getHidden();

            $variableTypes = $template->getVariableTypes();
            $transParams = $this->logTemplateHandler->parseTransParams($variableTypes, $entityVariables);

            try {
                $entries[$idx]['text'] = $this->translator->trans($template->getText(), $transParams, 'game');
            }
            catch (Exception $e) {
                $entries[$idx]['text'] = "null";
            }             
        }

        $limit = 0;
        if($this->user_handler->hasSkill($this->getActiveCitizen()->getUser(), 'manipulator'))
            $limit = 2;

        if($this->user_handler->hasSkill($this->getActiveCitizen()->getUser(), 'treachery'))
            $limit = 4;

        return $this->render( 'ajax/game/log_content.html.twig', [
            'entries' => $entries,
            'canHideEntry' => $this->getActiveCitizen()->getAlive() && $this->getActiveCitizen()->getProfession()->getHeroic() && $this->user_handler->hasSkill($this->getUser(), 'manipulator') && $this->getActiveCitizen()->getSpecificActionCounterValue(ActionCounter::ActionTypeRemoveLog) < $limit,
        ] );
    }

    protected function parseGazetteLog(GazetteLogEntry $gazetteLogEntry) {
        return $this->parseLog($gazetteLogEntry->getTemplate() !== null ? $gazetteLogEntry->getTemplate() : $gazetteLogEntry->getLogEntryTemplate(), $gazetteLogEntry->getVariables());
    }

    protected function parseLog( $template, array $variables ): String {
        $variableTypes = $template->getVariableTypes();
        $transParams = $this->logTemplateHandler->parseTransParams($variableTypes, $variables);

        try {
            $text = $this->translator->trans($template->getText(), $transParams, 'game');
        }
        catch (Exception $e) {
            $text = "null";
        }

        return $text;
    }

    /**
     * @Route("jx/game/landing", name="game_landing")
     * @return Response
     */
    public function landing(): Response
    {
        if (!$this->getActiveCitizen()->getAlive())
            return $this->redirect($this->generateUrl('soul_death'));
        elseif ($this->getActiveCitizen()->getProfession()->getName() === CitizenProfession::DEFAULT)
            return $this->redirect($this->generateUrl('game_jobs'));
        elseif (!$this->getActiveCitizen()->getHasSeenGazette())
            return $this->redirect($this->generateUrl('game_newspaper'));
        elseif ($this->getActiveCitizen()->getZone() && !$this->getActiveCitizen()->activeExplorerStats())
            return $this->redirect($this->generateUrl('beyond_dashboard'));
        elseif ($this->getActiveCitizen()->getZone() && $this->getActiveCitizen()->activeExplorerStats())
            return $this->redirect($this->generateUrl('exploration_dashboard'));
        else return $this->redirect($this->generateUrl('town_dashboard'));
    }

    /**
     * @Route("api/game/expert_toggle", name="game_toggle_expert_mode")
     * @return Response
     */
    public function toggle_expert_mode() {
        $this->entity_manager->persist( $this->getUser()->setExpert( !$this->getUser()->getExpert() ) );
        try {
            $this->entity_manager->flush();
        } catch (Exception $e) { return AjaxResponse::error(ErrorHelper::ErrorDatabaseException); }
        return AjaxResponse::success();
    }

    /**
     * @Route("jx/game/raventimes", name="game_newspaper")
     * @return Response
     */
    public function newspaper(): Response {
        if ($this->getActiveCitizen()->getAlive() && $this->getActiveCitizen()->getProfession()->getName() === CitizenProfession::DEFAULT)
            return $this->redirect($this->generateUrl('game_landing'));

        $in_town = $this->getActiveCitizen()->getZone() === null;
        $town = $this->getActiveCitizen()->getTown();
        $day = $town->getDay();
        $death_outside = $death_inside = [];

        $has_living_citizens = false;
        foreach ( $town->getCitizens() as $c )
            if ($c->getAlive()) {
                $has_living_citizens = true;
                break;
            }

        if (!$has_living_citizens && $this->getActiveCitizen()->getCauseOfDeath()->getRef() != CauseOfDeath::Radiations)
            return $this->redirect($this->generateUrl('game_landing'));

        /** @var Gazette $gazette */
        $gazette = $town->findGazette( $day );
        if (!$gazette) {
            $gazette = new Gazette();
            $gazette->setTown($town)->setDay($town->getDay());
            $town->addGazette($gazette);
        }

        $survivors = [];
        foreach ($town->getCitizens() as $citizen) {
            if(!$citizen->getAlive()) continue;
            $survivors[] = $citizen;
        }

        foreach ($gazette->getVictims() as $citizen) {
            if($citizen->getAlive()) continue;
            if ($citizen->getCauseOfDeath()->getRef() == CauseOfDeath::NightlyAttack)
                $death_inside[] = $citizen;
            else
                $death_outside[] = $citizen;
        }

        if (count($death_inside) > $gazette->getDeaths()) {
            $gazette->setDeaths(count($death_inside));
        }

        /** @var GazetteLogEntry[] $gazette_logs */
        $gazette_logs = $this->entity_manager->getRepository(GazetteLogEntry::class)->findBy(['gazette' => $gazette]);
        $text = '';
        $wind = "";
        if (count($gazette_logs) == 0) {
            // No Gazette texts! Let's generate some...
            if ($day == 1) {
                // TODO: Turn into LogEntryTemplate
                $text = "<p>" . $this->translator->trans('Heute Morgen ist kein Artikel erschienen...', [], 'game') . "</p>";
                if ($town->isOpen()){
                    $text .= "<p>" . $this->translator->trans('Die Stadt wird erst starten, wenn sie <strong>%population% Bürger hat</strong>.', ['%population%' => $town->getPopulation()], 'game') . "</p>" . "<a class='help-button'>" . "<div class='tooltip help'>" . $this->translator->trans("Falls sich dieser Zustand auch um Mitternacht noch nicht geändert hat, findet kein Zombieangriff statt. Der Tag wird dann künstlich verlängert.", [], 'global') . "</div>" . $this->translator->trans("Hilfe", [], 'global') . "</a>";
                } else {
                    $text .= $this->translator->trans('Fangt schon mal an zu beten, Bürger - die Zombies werden um Mitternacht angreifen!', [], 'game');
                }
            } else {
                // 1. TOWN
                if($town->getDevastated()){
                    $criteria = [
                        'name' => 'gazetteTownDevastated'
                    ];
                } else {
                    $criteria = [
                        'type' => GazetteEntryTemplate::TypeGazetteNoDeaths + (count($death_inside) < 3 ? count($death_inside) : 3),
                    ];
                }

templates/ajax/game/town/catapult.html.twig
{% extends "ajax/game/town/town.html.twig" %}
{% block title %}{{'Katapult'|trans({}, 'game')}}{% endblock %}
{% block content %}

    <h1 class="page-head">{{'Katapult'|trans({}, 'game')}}</h1>

    <div class="help">
        <strong>{{ 'Das Katapult ist ein wirklich mächtiges Instrument, um jeden beliebigen Gegenstand zu einer Zone in der Wüste zu schicken.'|trans({},'game') }}</strong>
        {{ 'Praktisch zur Versorgung aus der Ferne.'|trans({},'game') }}
        <p>{{ 'Denke daran, dass das Katapult manchmal sein Ziel verfehlt und den Gegenstand in eine angrenzende Zone befördert...'|trans({},'game')}}</p>
        <p>
            {% if is_catapult_master %}
                <strong>{{'Du wurdest als Verantwortlicher für das Katapult bestimmt!'|trans({},'game')}}</strong>
                {{'Wähle einen Gegenstand aus deinem Inventar und gib die Zielkoordinaten ein.'|trans({},'game')}}
            {% elseif catapult_master is not null %}
                {{'Unser Katapult wird von dem vom Schicksal auserwählten Bürger %citizen% gesteuert. Sollte ihm etwas Schreckliches zustoßen, könnte dann ein neuer Bürger gewählt werden.'|trans({'%citizen%': ('<span class="link" x-ajax-href="' ~ path('town_visit', {id: catapult_master.id}) ~ '"><b>' ~ catapult_master.user.name ~ '</b></span>')},'game')|raw}}
            {% endif %}
        </p>
        {% if catapult_improved %}
            {{ 'Die Aktivierung des Katapults kostet %ap%.'|trans({'%ap%': '<div class="ap">2</div>'},'game')|raw }}
        {% else %}
            {{ 'Die Aktivierung des Katapults kostet %ap% (diese Kosten können durch den Bau eines besseren Katapults gesenkt werden).'|trans({'%ap%': '<div class="ap">4</div>'},'game')|raw }}
        {% endif %}
    </div>

    {% if catapult_master is null %}
        <p>
            <button id="cata_new">{{ 'Einen zufälligen Bürger als Katapult-Bediener auslosen'|trans({},'game') }}</button>
        </p>
    {% endif %}

    {% if is_catapult_master %}
        <div class="row">
            <div class="cell-small rw-10 ro-7 rw-md-14 ro-md-5 rw-sm-24 ro-sm-0">
                <div class="note">
                    <div class="center"><strong>{{ 'Zu verschickender Gegenstand:'|trans({},'game') }}</strong></div>
                    <div><label><select id="cata_what">
                        <option value="-1">-- {{ 'Gegenstand auswählen'|trans({},'game') }} --</option>
                        {% for item in app.user.activeCitizen.inventory.items %}
                            {# @var item \App\Entity\Item #}
                            {% if not item.essential and not item.broken %}
                                <option value="{{ item.id }}">{{ item.prototype.label|trans({},'items') }}</option>
                            {% endif %}
                        {% endfor %}
                    </select></label></div>
                    <div class="row">
                        <div class="padded cell rw-6">
                            <div class="center"><label for="cata_x"><strong>X</strong></label></div>
                            <input id="cata_x" type="number" />
                        </div>
                        <div class="padded cell rw-6">
                            <div class="center"><label for="cata_y"><strong>Y</strong></label></div>
                            <input id="cata_y" type="number" />
                        </div>
                    </div>
                    <div class="row"><div class="padded cell rw-12"><button id="cata_do">{{ 'Gegenstand katapultieren'|trans({},'game') }}</button></div></div>
                </div>
            </div>
        </div>
    {% endif %}

    <div class="row">
        <h5>{% trans from 'game' %}Katapultregister{% endtrans %}</h5>
        <div class="cell rw-12">
            {% embed "ajax/game/log.html.twig" with {'log_content': log, 'log_source': path('town_catapult_log_controller') } %}
            {% endembed %}
        </div>
    </div>

{% endblock %}
{% block js %}
    {{ parent() }}
    <script>
        {% embed "scripts/log.js.twig" %}{% endembed %}

        {% if is_catapult_master %}
            $.html.addEventListenerAll('#cata_do', 'click', function () {
                const item = parseInt(document.getElementById('cata_what').value);
                const x = parseInt(document.getElementById('cata_x').value);
                const y = parseInt(document.getElementById('cata_y').value);

                if (item <= 0) {
                    $.html.message('error', '{{ 'Bitte wähle einen Gegenstand.'|trans({},'game') }}');
                    return;
                }
                if (isNaN(x) || isNaN(y)) {
                    $.html.message('error', '{{ 'Bitte gib die Zielkoordinaten ein.'|trans({},'game') }}');
                    return;
                }

                $.ajax.easySend( '{{ path('town_catapult_do_controller') }}', {item: item, x: x, y: y},
                    function () {
                        $.ajax.load(null, '{{ path('town_catapult') }}', true);
                    } );
            });
        {% endif %}

        {% if catapult_master is null %}
            $.html.addEventListenerAll('#cata_new', 'click', function () {
                $.ajax.easySend( '{{ path('town_catapult_assign_controller') }}', {},
                    function () {
                        $.ajax.load(null, '{{ path('town_catapult') }}', true);
                    } );
            });
        {% endif %}
    </script>
{% endblock %}

templates/ajax/game/town/door.html.twig
{% extends "ajax/game/town/town.html.twig" %}
{% block title %}{{'Das Stadttor von "%townname%"'|trans({"%townname%": town.name}, 'game')|raw}}{% endblock %}
{% block tutorial %}
    <div x-tutorial-content="4.text3" class="toplevel text arrow-down">
        <div class="help">
            {% if town.door %}
                <p>{% trans from "help" %}
                        Das Stadttor ist geöffnet.
                    {% endtrans %}</p>
                <p>{% trans from "help" %}
                        Klick hier, um <strong>in die Wüste zu gehen</strong>... Sei jedoch vorsichtig!
                    {% endtrans %}</p>
                <button x-advance-tutorial="complete">{{ 'Weiter...'|trans({},'help') }}</button>
            {% else %}
                <p>{% trans from "help" %}
                        Du kannst <strong>das Stadttor</strong> in diesem Bereich öffnen... Achtung: Wenn das Tor beim allnächtlichen <strong>Angriff der Zombiehorde</strong> offen steht, kann das für die Stadt fatale Folgen haben...<strong></strong>
                    {% endtrans %}</p>
            {% endif %}
        </div>
    </div>
{% endblock %}
{% block content %}
    {% set hour = "now"|date("G") %}
    <div class="row">
        <div class="cell rw-12 town-banner town-banner-door-{% if town.door %}open{% else %}closed{% endif%} time-{{ hour }} {% if town.isNight %}night{% endif %}"></div>
    </div>

    {% embed "ajax/game/town/door_tabs.html.twig" with {'door_section': door_section, 'has_battlement': has_battlement} %}
    {% endembed %}

    <div class="row town-summary">
        <div class="padded cell rw-4 row-header"><img src="{{ asset('build/images/item/item_plate.gif') }}" alt="" /> {{'Stadtverteidigung'|trans({}, 'game')}}</div>
        <div class="padded cell rw-8 row-detail">{{def}} <img src="{{ asset('build/images/icons/small_def.gif') }}" alt="" /> (<span class="link" x-ajax-href="{{ path('town_dashboard') }}">{{'Details ansehen'|trans({}, 'game')}}</span>)</div>
        <div class="padded cell rw-4 row-header"><img src="{{ asset('build/images/item/item_door.gif') }}" alt="" /> {{'Lage'|trans({}, 'game')}}</div>
        <div class="padded cell rw-8 row-detail">{% if town.door %}
                <span class="warning">{{'Stadttor geöffnet'|trans({}, 'game')}}</span> <span class="small">(<span class="link" x-ajax-href="{{ path("town_citizens") }}">{{'Wer ist draußen?'|trans({}, 'game')}}</span>)</span>
            {% else %}
                {{'Stadttor geschlossen'|trans({}, 'game')}}
            {% endif %} </div>
    </div>

    <div class="row">

        <div class="padded cell rw-6 rw-md-12">

            {% if not app.user.expert %}

                {% set has_packed_food = false %}
                {% set has_packed_water = false %}
                {% for item in app.user.activeCitizen.inventory.items %}
                    {% if item.prototype.hasProperty('is_water') %}{% set has_packed_water = true %}{% endif %}
                    {% if item.prototype.hasProperty('food') %}    {% set has_packed_food  = true %}{% endif %}
                {% endfor %}

                {% if not has_packed_food and not has_packed_water %}
                    <div x-conditional-help="door_equipment" class="no-arrow">
                        <p>{% trans from "help" %}
                                Es wäre vielleicht nicht verkehrt etwas <strong>Proviant</strong> (Nahrung und/oder Wasser) einzupacken, bevor du die Stadt verlässt... Gehe dazu in den Bereich <strong>Mein Zuhause</strong>.
                            {% endtrans %}</p>
                        <button x-confirm-conditional-help="door_equipment" x-temp="1">{{ 'Schließen'|trans({},'global') }}</button>
                    </div>
                {% endif %}
            {% endif %}

            <div class="help">
                {% trans from 'game' %}
                    Du kannst von hier aus die Stadt verlassen und die Außenwelt erkunden. Vergiss aber nicht, um Mitternacht das Tor zu schließen!
                {% endtrans %}
            </div>

            {% if banished %}
                <div class="note note-warning">
                    {% trans from 'game' %}
                        Du wurdest verbannt und kannst daher das Stadttor weder öffnen noch schließen.
                    {% endtrans %}
                </div>
            {% endif %}

            <h5>{% trans from 'game' %}Meine Aktionen{% endtrans %}</h5>
            {% if not banished %}
                {% if town.door %}
                    <button id="door_closer" {% if town.devastated %}disabled{% endif %}><img alt="" src="{{ asset('build/images/icons/small_action.gif') }}" />{% trans from 'game' %}Tor schließen{% endtrans %} (<div class="ap">1</div>)</button>
                {% else %}
                    <button id="door_opener" {% if door_locked %}disabled{% endif %}><img alt="" src="{{ asset('build/images/icons/small_action.gif') }}" />{% trans from 'game' %}Tor öffnen{% endtrans %} (<div class="ap">1</div>)</button>
                {% endif %}
            {% endif %}
            {% if show_ventilation %}
                <button id="door_exit_hero"{% if not allow_ventilation or not can_go_out %}disabled{% endif %}><img alt="" src="{{ asset('build/images/icons/star.gif') }}">{% trans from 'game' %}Durch die Lüftungsschächte klettern{% endtrans %}</button>
            {% endif %}
            {% if show_sneaky %}
                <button id="door_exit_sneak" {% if not town.door or not can_go_out %}disabled{% endif %}><img alt="" src="{{ asset('build/images/roles/ghoul.gif') }}">{% trans from 'game' %}Aus der Stadt schleichen{% endtrans %}</button>
            {% endif %}
            <button id="door_exit" {% if not town.door or not can_go_out %}disabled{% endif %}><img alt="" src="{{ asset('build/images/icons/small_move.gif') }}" />{% trans from 'game' %}Stadt verlassen{% endtrans %}</button>
            <button x-ajax-href="{{ path('town_routes') }}"><img alt="" src="{{ asset('build/images/item/item_bagxl.gif') }}" />{{ 'Route planen...'|trans({},'game') }}</button>
        </div>
        <div class="padded cell rw-6 rw-md-12">
            {% embed "ajax/game/map.html.twig" with {'default_zoom': 0, 'default_show_zone': false, 'allow_zone_view': false, 'in_town': true, 'chaos': chaos, 'is_shaman': is_shaman, 'map': map_data, 'chaos': town.chaos} %}
            {% endembed %}
        </div>
    </div>

    <p class="ambiant">
        {{'Das Stadttor ist Teil einer Festungsmauer, die den Großteil der Zombies abwehrt. Solltest du vergessen es am Abend zu schließen, kannst du dich auf Qualen einstellen, die deine schlimmsten Alpträume weit übertreffen.'|trans({}, 'game')}}
    </p>

    <div class="row">
        <h5>{{ 'Stadttor-Register'|trans({},'game') }}</h5>
        <div class="cell rw-12">
            {% embed "ajax/game/log.html.twig" with {'log_content': log, 'log_source': path('town_door_log_controller') } %}
            {% endembed %}
        </div>
    </div>
{% endblock %}
{% block js %}
    {{ parent() }}
    <script>
        {% embed "scripts/map.js.twig" with {'map': map_data} %}{% endembed %};
        {% embed "scripts/log.js.twig" %}{% endembed %}

        const handleDoor = function(element, action) {
            if (!element) return;
            element.addEventListener('click', function() {
                if (!confirm('{{ 'Bestätigen?'|trans({},'global')|e('js') }}'))
                    return;
                $.ajax.easySend( '{{ path('town_door_control_controller') }}', {
                        action: action
                    },
                    function () {
                        $.ajax.load(null, '{{ path('town_door') }}', true);
                    } );
            });
        };

        handleDoor( document.getElementById('door_opener'), 'open' );
        handleDoor( document.getElementById('door_closer'), 'close' );

        document.getElementById('door_exit').addEventListener('click', function() {
            $.ajax.easySend( '{{ path('town_door_exit_controller') }}', {},
                function () {
                    $.ajax.load(null, '{{ path('game_landing') }}', true);
                } );
        });

        {% if show_ventilation and allow_ventilation %}
        document.getElementById('door_exit_hero').addEventListener('click', function() {
            $.ajax.easySend( '{{ path('town_door_exit_controller', {'special': 'hero'}) }}', {},
                function () {
                    $.ajax.load(null, '{{ path('game_landing') }}', true);
                } );
        });
        {% endif %}

        {% if show_sneaky %}
        document.getElementById('door_exit_sneak').addEventListener('click', function() {
            $.ajax.easySend( '{{ path('town_door_exit_controller', {'special': 'sneak'}) }}', {},
                function () {
                    $.ajax.load(null, '{{ path('game_landing') }}', true);
                } );
        });
        {% endif %}
    </script>
{% endblock %}

templates/ajax/game/town/door_tabs.html.twig
<ul class="tabs plain">
    <li class="tab {% if door_section == 'door' %}selected{% endif %}">
        <div class="tab-link" x-ajax-sticky x-ajax-href="{{ path('town_door') }}">{% trans from 'game' %}Stadttor{% endtrans %}</div>
    </li>
    <li class="tab {% if door_section == 'planner' %}selected{% endif %}">
        <div class="tab-link" x-ajax-sticky x-ajax-href="{{ path('town_routes') }}">{% trans from 'game' %}Expeditionen{% endtrans %}</div>
    </li>
    {% if has_battlement %}
        <li class="tab {% if door_section == 'nightwatch' %}selected{% endif %}">
            <div class="tab-link" x-ajax-sticky x-ajax-href="{{ path('town_nightwatch') }}">{% trans from 'game' %}Wächt{% endtrans %}</div>
        </li>
    {% endif %}
</ul>